"use client";

import { useMemo, useState } from "react";
import { DataTable, type DataTableColumn } from "@/components/data/data-table";
import { PaginationControls } from "@/components/data/pagination-controls";
import { SearchFilterBar } from "@/components/data/search-filter-bar";
import { SelectField } from "@/components/forms/select-field";
import { ErrorState } from "@/components/shared/error-state";
import { LoadingState } from "@/components/shared/loading-state";
import { PageHeader } from "@/components/shared/page-header";
import { PermissionGuard } from "@/components/shared/permission-guard";
import { StatusBadge } from "@/components/shared/status-badge";
import { stockMovementTypes } from "@/features/inventory/schemas";
import { useInventoryItems, useStockMovements } from "@/features/inventory/hooks";
import type { StockMovement } from "@/features/inventory/types";
import { ALL, formatInventoryDate, formatQuantity } from "@/features/inventory/utils";

export function StockMovementsPage() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [type, setType] = useState(ALL);
  const [itemId, setItemId] = useState(ALL);
  const items = useInventoryItems({ page: 1, limit: 100, sortBy: "name", sortOrder: "asc" });
  const movements = useStockMovements({ page, limit: 20, search: search || undefined, type: type === ALL ? undefined : type as StockMovement["type"], inventoryItemId: itemId === ALL ? undefined : itemId, sortBy: "movementDate", sortOrder: "desc" });
  const itemOptions = useMemo(() => [{ value: ALL, label: "All items" }, ...(items.data?.data ?? []).map((item) => ({ value: item.id, label: `${item.name} (${item.itemCode})` }))], [items.data?.data]);
  const columns: DataTableColumn<StockMovement>[] = [
    { key: "date", header: "Date", render: (row) => formatInventoryDate(row.movementDate) },
    { key: "item", header: "Item", render: (row) => row.inventoryItem?.name ?? "-" },
    { key: "type", header: "Type", render: (row) => <StatusBadge status={row.type} /> },
    { key: "quantity", header: "Quantity", render: (row) => formatQuantity(row.quantity, row.inventoryItem?.unit) },
    { key: "previous", header: "Previous", render: (row) => formatQuantity(row.previousStock, row.inventoryItem?.unit) },
    { key: "new", header: "New Stock", render: (row) => formatQuantity(row.newStock, row.inventoryItem?.unit) },
    { key: "reason", header: "Reason", render: (row) => row.reason ?? "-" },
  ];
  return (
    <PermissionGuard permission="inventory.view" fallback={<ErrorState title="Permission required" message="You do not have access to stock movements." />}>
      <div className="flex flex-col gap-6">
        <PageHeader title="Stock Movements" description="Stock movement ledger generated by receiving and adjustments." />
        <SearchFilterBar value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search movement reasons" filters={<><SelectField value={type} onValueChange={(value) => { setType(value); setPage(1); }} options={[{ value: ALL, label: "All types" }, ...stockMovementTypes.map((value) => ({ value, label: value }))]} /><SelectField value={itemId} onValueChange={(value) => { setItemId(value); setPage(1); }} options={itemOptions} /></>} onReset={() => { setSearch(""); setType(ALL); setItemId(ALL); setPage(1); }} />
        {movements.isLoading ? <LoadingState rows={6} /> : null}
        {movements.error ? <ErrorState title="Unable to load stock movements" message={movements.error instanceof Error ? movements.error.message : undefined} /> : null}
        {!movements.isLoading && !movements.error ? <><DataTable columns={columns} rows={movements.data?.data ?? []} getRowKey={(row) => row.id} emptyTitle="No stock movements found" /><PaginationControls page={movements.data?.meta.page ?? page} totalPages={movements.data?.meta.totalPages ?? 1} onPageChange={setPage} /></> : null}
      </div>
    </PermissionGuard>
  );
}
