import { apiRequest } from "@/lib/api/client";
import type {
  ChangePayrollRunStatusPayload,
  CreatePayrollPeriodPayload,
  CreatePayrollRunPayload,
  CreateSalaryAdvancePayload,
  CreateSalaryAssignmentPayload,
  CreateSalaryStructurePayload,
  ListQuery,
  PayrollPeriod,
  PayrollPeriodResult,
  PayrollRun,
  PayrollRunQuery,
  PayrollRunResult,
  PayslipQuery,
  PayslipResult,
  SalaryAdvance,
  SalaryAdvanceQuery,
  SalaryAdvanceResult,
  SalaryAssignment,
  SalaryAssignmentQuery,
  SalaryAssignmentResult,
  SalaryStructure,
  SalaryStructureResult,
  UpdatePayrollRunPayload,
} from "@/features/payroll/types";

export const payrollApi = {
  structures: (params: ListQuery) => apiRequest<SalaryStructureResult>({ url: "/payroll/salary-structures", method: "GET", params }),
  createStructure: (data: CreateSalaryStructurePayload) => apiRequest<SalaryStructure>({ url: "/payroll/salary-structures", method: "POST", data }),
  assignments: (params: SalaryAssignmentQuery) => apiRequest<SalaryAssignmentResult>({ url: "/payroll/salary-assignments", method: "GET", params }),
  createAssignment: (data: CreateSalaryAssignmentPayload) => apiRequest<SalaryAssignment>({ url: "/payroll/salary-assignments", method: "POST", data }),
  advances: (params: SalaryAdvanceQuery) => apiRequest<SalaryAdvanceResult>({ url: "/payroll/advances", method: "GET", params }),
  createAdvance: (data: CreateSalaryAdvancePayload) => apiRequest<SalaryAdvance>({ url: "/payroll/advances", method: "POST", data }),
  periods: (params: ListQuery) => apiRequest<PayrollPeriodResult>({ url: "/payroll/periods", method: "GET", params }),
  createPeriod: (data: CreatePayrollPeriodPayload) => apiRequest<PayrollPeriod>({ url: "/payroll/periods", method: "POST", data }),
  runs: (params: PayrollRunQuery) => apiRequest<PayrollRunResult>({ url: "/payroll/runs", method: "GET", params }),
  createRun: (data: CreatePayrollRunPayload) => apiRequest<PayrollRun>({ url: "/payroll/runs", method: "POST", data }),
  run: (id: string) => apiRequest<PayrollRun>({ url: `/payroll/runs/${id}`, method: "GET" }),
  updateRun: (id: string, data: UpdatePayrollRunPayload) => apiRequest<PayrollRun>({ url: `/payroll/runs/${id}`, method: "PATCH", data }),
  changeRunStatus: (id: string, data: ChangePayrollRunStatusPayload) => apiRequest<PayrollRun>({ url: `/payroll/runs/${id}/status`, method: "PATCH", data }),
  payslips: (employeeId: string, params: PayslipQuery) => apiRequest<PayslipResult>({ url: `/payroll/payslips/${employeeId}`, method: "GET", params }),
};
