"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, Play, Plus, Save, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { DataTable, type DataTableColumn } from "@/components/data/data-table";
import { PaginationControls } from "@/components/data/pagination-controls";
import { SelectField } from "@/components/forms/select-field";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { DataCard } from "@/components/shared/data-card";
import { ErrorState } from "@/components/shared/error-state";
import { LoadingState } from "@/components/shared/loading-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { useChangePayrollRunStatus, useCreatePayrollRun, usePayrollRun, usePayrollRuns, useUpdatePayrollRun } from "@/features/payroll/hooks";
import { payrollRunSchema, type PayrollRunFormValues } from "@/features/payroll/schemas";
import type { PayrollLineItem, PayrollPeriod, PayrollRun, PayrollRunStatus } from "@/features/payroll/types";
import { ALL, formatPayrollDate, formatPayrollMoney, legalPayrollActions, NONE, payrollEmployeeName, payrollErrorMessage, statusActionLabel } from "@/features/payroll/utils";

export function PayrollRuns({ periods, canManage }: { periods: PayrollPeriod[]; canManage: boolean }) {
  const [page, setPage] = useState(1); const [periodId, setPeriodId] = useState(ALL); const [status, setStatus] = useState(ALL); const [selectedId, setSelectedId] = useState("");
  const query = usePayrollRuns({ page, limit: 10, payrollPeriodId: periodId === ALL ? undefined : periodId, status: status === ALL ? undefined : status as PayrollRunStatus, sortBy: "createdAt", sortOrder: "desc" });
  const columns: DataTableColumn<PayrollRun>[] = [
    { key: "period", header: "Period", render: (row) => <div><p className="font-medium">{row.payrollPeriod?.name ?? "Unknown period"}</p><p className="text-xs text-muted-foreground">{formatPayrollDate(row.payrollPeriod?.startDate)} – {formatPayrollDate(row.payrollPeriod?.endDate)}</p></div> },
    { key: "status", header: "Status", render: (row) => <StatusBadge status={row.status} /> },
    { key: "employees", header: "Employees", render: (row) => row._count?.lineItems ?? 0 },
    { key: "gross", header: "Gross", render: (row) => formatPayrollMoney(row.totalGross) },
    { key: "deductions", header: "Deductions", render: (row) => formatPayrollMoney(row.totalDeductions) },
    { key: "net", header: "Net", render: (row) => <span className="font-medium">{formatPayrollMoney(row.totalNet)}</span> },
    { key: "created", header: "Created", render: (row) => formatPayrollDate(row.createdAt) },
    { key: "actions", header: "Actions", render: (row) => <Button type="button" size="sm" variant="ghost" onClick={() => setSelectedId(row.id)}><Eye className="size-4" />View</Button> },
  ];
  return <><DataCard title="Payroll runs" description="All amounts are generated by the backend from assignments, attendance, approved leave, holidays and active advances." action={canManage ? <RunDialog periods={periods} /> : undefined}><div className="space-y-4"><div className="flex flex-wrap items-center gap-2 rounded-lg border border-border bg-card p-3"><SelectField value={periodId} onValueChange={(value) => { setPeriodId(value); setPage(1); }} options={[{ value: ALL, label: "All periods" }, ...periods.map((period) => ({ value: period.id, label: period.name }))]} className="w-56" /><SelectField value={status} onValueChange={(value) => { setStatus(value); setPage(1); }} options={[{ value: ALL, label: "All statuses" }, ...(["DRAFT", "PROCESSING", "APPROVED", "PAID", "CANCELLED"] as const).map((value) => ({ value, label: value.replaceAll("_", " ") }))]} className="w-44" /><Button type="button" variant="outline" onClick={() => { setPeriodId(ALL); setStatus(ALL); setPage(1); }}><SlidersHorizontal className="size-4" />Reset</Button></div>{query.isLoading ? <LoadingState rows={5} /> : query.error ? <ErrorState title="Unable to load payroll runs" message={payrollErrorMessage(query.error)} onRetry={() => void query.refetch()} /> : <><DataTable columns={columns} rows={query.data?.data ?? []} getRowKey={(row) => row.id} emptyTitle="No payroll runs" /><PaginationControls page={page} totalPages={query.data?.meta.totalPages ?? 1} onPageChange={setPage} /></>}</div></DataCard><RunDetailDialog id={selectedId} open={Boolean(selectedId)} onOpenChange={(open) => { if (!open) setSelectedId(""); }} canManage={canManage} /></>;
}

function RunDialog({ periods }: { periods: PayrollPeriod[] }) {
  const [open, setOpen] = useState(false); const [formError, setFormError] = useState<string | null>(null); const mutation = useCreatePayrollRun();
  const form = useForm<PayrollRunFormValues>({ resolver: zodResolver(payrollRunSchema), defaultValues: { payrollPeriodId: NONE, notes: "" } });
  const selectedPeriod = useWatch({ control: form.control, name: "payrollPeriodId" });
  async function submit(values: PayrollRunFormValues) { setFormError(null); try { await mutation.mutateAsync({ payrollPeriodId: values.payrollPeriodId, notes: values.notes?.trim() || undefined }); setOpen(false); form.reset(); } catch (error) { setFormError(payrollErrorMessage(error)); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button type="button" />}><Plus className="size-4" />Create payroll run</DialogTrigger><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Create payroll run</DialogTitle><DialogDescription>This calculates every eligible employee from their active salary assignment, attendance, leave, holidays and advances. It does not recover advances until the run is marked paid.</DialogDescription></DialogHeader><form className="space-y-4"><div><p className="mb-1.5 text-sm font-medium">Payroll period</p><SelectField value={selectedPeriod} onValueChange={(value) => form.setValue("payrollPeriodId", value, { shouldValidate: true })} options={[{ value: NONE, label: "Select period" }, ...periods.map((period) => ({ value: period.id, label: `${period.name} · ${formatPayrollDate(period.startDate)} – ${formatPayrollDate(period.endDate)}` }))]} />{form.formState.errors.payrollPeriodId?.message ? <p className="mt-1 text-xs text-destructive">{form.formState.errors.payrollPeriodId.message}</p> : null}</div><div><p className="mb-1.5 text-sm font-medium">Notes</p><Textarea {...form.register("notes")} placeholder="Optional run context" /></div>{formError ? <ErrorState title="Unable to create run" message={formError} /> : null}</form><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><ConfirmDialog trigger={<Button type="button" disabled={mutation.isPending}><Play className="size-4" />{mutation.isPending ? "Generating…" : "Generate draft"}</Button>} title="Generate this payroll run?" description="The server will calculate and persist the run, all employee lines and payslip metadata atomically." confirmLabel="Generate payroll" onConfirm={() => void form.handleSubmit(submit)()} /></DialogFooter></DialogContent></Dialog>;
}

function RunDetailDialog({ id, open, onOpenChange, canManage }: { id: string; open: boolean; onOpenChange: (open: boolean) => void; canManage: boolean }) {
  const query = usePayrollRun(id, open); const transition = useChangePayrollRunStatus(); const run = query.data; const [actionError, setActionError] = useState<string | null>(null);
  async function changeStatus(status: PayrollRunStatus) { if (!run) return; setActionError(null); try { await transition.mutateAsync({ id: run.id, data: { status } }); } catch (error) { setActionError(payrollErrorMessage(error)); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-6xl"><DialogHeader><DialogTitle>Payroll run</DialogTitle><DialogDescription>{run?.payrollPeriod?.name ?? "Loading period"} · Authoritative financial detail</DialogDescription></DialogHeader>{query.isLoading ? <LoadingState rows={6} /> : query.error ? <ErrorState title="Unable to load run" message={payrollErrorMessage(query.error)} onRetry={() => void query.refetch()} /> : run ? <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Status" value={<StatusBadge status={run.status} />} /><Summary label="Employees" value={String(run.lineItems?.length ?? 0)} /><Summary label="Gross" value={formatPayrollMoney(run.totalGross)} /><Summary label="Net" value={formatPayrollMoney(run.totalNet)} /></div>{canManage && legalPayrollActions[run.status].length > 0 ? <div className="flex flex-wrap gap-2 rounded-lg border border-border bg-muted/30 p-3">{legalPayrollActions[run.status].map((next) => <ConfirmDialog key={next} trigger={<Button type="button" variant={next === "CANCELLED" ? "destructive" : "default"} size="sm" disabled={transition.isPending}>{statusActionLabel(next)}</Button>} title={`${statusActionLabel(next)}?`} description={next === "PAID" ? "This finalizes the run, publishes payslip metadata and posts each planned salary-advance recovery exactly once." : `This changes the run from ${run.status} to ${next}.`} confirmLabel={statusActionLabel(next)} destructive={next === "CANCELLED"} onConfirm={() => void changeStatus(next)} />)}</div> : null}{actionError ? <ErrorState title="Unable to change run status" message={actionError} /> : null}{canManage && ["DRAFT", "PROCESSING"].includes(run.status) ? <RunNotesEditor key={`${run.id}:${run.notes ?? ""}`} run={run} /> : run.notes ? <div className="rounded-lg border border-border p-3"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Notes</p><p className="mt-1 text-sm">{run.notes}</p></div> : null}<PayrollLineTable rows={run.lineItems ?? []} /></div> : null}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Close</Button></DialogFooter></DialogContent></Dialog>;
}

function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-lg border border-border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 text-lg font-semibold">{value}</div></div>; }

function RunNotesEditor({ run }: { run: PayrollRun }) { const [notes, setNotes] = useState(run.notes ?? ""); const [error, setError] = useState<string | null>(null); const mutation = useUpdatePayrollRun(); async function save() { setError(null); try { await mutation.mutateAsync({ id: run.id, data: { notes: notes.trim() || undefined } }); } catch (caught) { setError(payrollErrorMessage(caught)); } } return <div className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">Run notes</p><Button type="button" size="sm" variant="outline" onClick={() => void save()} disabled={mutation.isPending}><Save className="size-4" />Save notes</Button></div><Textarea className="mt-2" value={notes} onChange={(event) => setNotes(event.target.value)} />{error ? <p className="mt-2 text-sm text-destructive">{error}</p> : null}</div>; }

function PayrollLineTable({ rows }: { rows: PayrollLineItem[] }) {
  const columns: DataTableColumn<PayrollLineItem>[] = [
    { key: "employee", header: "Employee", render: (row) => <div><p className="font-medium">{payrollEmployeeName(row.employee)}</p><p className="text-xs text-muted-foreground">{row.employee?.employeeCode ?? "—"}</p></div> },
    { key: "days", header: "Working / payable", render: (row) => `${Number(row.workingDays)} / ${Number(row.payableDays)}` },
    { key: "leave", header: "Leave / absent", render: (row) => `${Number(row.leaveDays)} / ${Number(row.absentDays)}` },
    { key: "monthly", header: "Monthly gross", render: (row) => formatPayrollMoney(row.salaryAssignment?.monthlyGross) },
    { key: "gross", header: "Gross", render: (row) => formatPayrollMoney(row.grossEarnings) },
    { key: "deductions", header: "Deductions", render: (row) => <div><p>{formatPayrollMoney(row.totalDeductions)}</p>{Number(row.advanceDeduction) > 0 ? <p className="text-xs text-muted-foreground">Advance {formatPayrollMoney(row.advanceDeduction)}</p> : null}</div> },
    { key: "net", header: "Net pay", render: (row) => <span className="font-medium">{formatPayrollMoney(row.netPay)}</span> },
    { key: "payslip", header: "Payslip", render: (row) => row.payslip ? <div><StatusBadge status={row.payslip.status} /><p className="mt-1 text-xs text-muted-foreground">{row.payslip.payslipNumber}</p></div> : "—" },
  ];
  return <DataCard title="Employee line items" description="Browser values are read-only outputs from the stored payroll run."><DataTable columns={columns} rows={rows} getRowKey={(row) => row.id} emptyTitle="No employee lines" /></DataCard>;
}
