export enum ApprovalStepApproverTypeDto {
  USER = 'USER',
  EMPLOYEE = 'EMPLOYEE',
  ROLE = 'ROLE',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  REPORTING_MANAGER = 'REPORTING_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  HR_MANAGER = 'HR_MANAGER',
  ADMIN = 'ADMIN',
}

export enum ApprovalEntityTypeDto {
  LEAVE = 'LEAVE',
  ATTENDANCE_CORRECTION = 'ATTENDANCE_CORRECTION',
  EXPENSE_CLAIM = 'EXPENSE_CLAIM',
  PURCHASE_REQUEST = 'PURCHASE_REQUEST',
  PAYROLL_RUN = 'PAYROLL_RUN',
  VENDOR_BILL = 'VENDOR_BILL',
  INVOICE = 'INVOICE',
  QUOTATION = 'QUOTATION',
  ASSET_ASSIGNMENT = 'ASSET_ASSIGNMENT',
  DOCUMENT = 'DOCUMENT',
  CUSTOM = 'CUSTOM',
}

export enum ApprovalRequestStatusDto {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ApprovalStepStatusDto {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
}

export enum ApprovalActionDto {
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  CANCEL = 'CANCEL',
  DELEGATE = 'DELEGATE',
  COMMENT = 'COMMENT',
}
